### ISSUE TITLE
Improve doctests handling

### ISSUE THREAD

**Issue by HelgeKrueger** [messense/nh3#73]
__Note__: I don't expect this to be easily doable in this project. It would either belong into pytest or maturin. This is just where this issue arose for me.

This issue arose while implementing https://github.com/messense/nh3/pull/72

By adding

```toml
[tool.pytest.ini_options]
addopts = '--doctest-glob="*.rst"'
```

to pyproject.toml, one can run the docstrings in `docs/index.rst` using pytest.  See [here](https://docs.pytest.org/en/6.2.x/doctest.html).

Unfortunately, this doesn't run the doctests in `src/lib.rs`.

Question: Can one adopt the tooling to also run these?
